# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    ls
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    filePath: './scripts/buildProject.sh'
  displayName: 'Build and test sources'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Avaliação Gratuita(18441764-decb-42f5-9121-06d30147bbbe)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './scripts/clearResource.sh'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Avaliação Gratuita(18441764-decb-42f5-9121-06d30147bbbe)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './scripts/initializeResource.sh'
  