# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    ls
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    filePath: './scripts/buildProject.sh'
  displayName: 'Build and test sources'
- task: Bash@3
  inputs:
    filePath: './scripts/clearResource.sh'
  displayName: 'Clear resources case exists'
- task: Bash@3
  inputs:
    filePath: './scripts/initializeResource.sh'
  displayName: 'Create resources on Azure'
  